variables:
  AUDIT_AWS_RDS_ALERT_LIST:
    description: "Which alerts would you like to check for? (Default is all RDS alerts)"
    required: true
    type: array
    default:
      - rds-short-backup-retention-period
      - rds-no-auto-minor-version-upgrade
      - rds-db-publicly-accessible
      - rds-inventory
  AUDIT_AWS_RDS_ALERT_RECIPIENT:
    description: "Enter the email address(es) that will receive notifiers. If more than one, separate each with a comma."
    required: true
    type: string
    default:
  AUDIT_AWS_RDS_ALLOW_EMPTY:
    description: "Would you like to receive empty reports? Options - true / false. Default is false."
    required: true
    type: string
    default: false
  AUDIT_AWS_RDS_SEND_ON:
    description: "Send reports always or only when there is a change? Options - always / change. Default is change."
    required: true
    type: string
    default: "change"
  AUDIT_AWS_RDS_REGIONS:
    description: "List of AWS regions to check. Default is us-east-1,us-west-1,us-west-2."
    required: true
    type: array
    default:
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2
        - eu-west-1
  AUDIT_AWS_RDS_ROLLUP_REPORT:
      description: "Would you like to send a Summary ELB report? Options - notify / nothing. Default is no / nothing."
      required: true
      type: string
      default: "nothing"
  AUDIT_AWS_RDS_HTML_REPORT:
      description: notify or nothing
      required: true
      type: string
      default: "notify"
  AUDIT_AWS_RDS_OWNER_TAG:
      description: "Enter an AWS tag whose value is an email address of owner of the ELB object. (Optional)"
      required: false
      type: string
      default: "NOT_A_TAG"
